import { defineConfig } from "vite-plus";

// the legacy Next.js app is kept as a frozen reference and excluded from
// the Vite+ toolchain; routeTree.gen.ts is generated by TanStack Router
const checkIgnorePatterns = ["apps/portfolio-2025/**", "**/routeTree.gen.ts"];

export default defineConfig({
  staged: {
    "*": "vp check --fix",
  },
  fmt: { ignorePatterns: checkIgnorePatterns },
  lint: {
    ignorePatterns: checkIgnorePatterns,
    options: { typeAware: true, typeCheck: true },
  },
  run: {
    cache: true,
  },
});
