/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OpenfgcRouteImport } from './routes/openfgc'
import { Route as IndexRouteImport } from './routes/index'

const OpenfgcRoute = OpenfgcRouteImport.update({
  id: '/openfgc',
  path: '/openfgc',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/openfgc': typeof OpenfgcRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/openfgc': typeof OpenfgcRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/openfgc': typeof OpenfgcRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/openfgc'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/openfgc'
  id: '__root__' | '/' | '/openfgc'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OpenfgcRoute: typeof OpenfgcRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/openfgc': {
      id: '/openfgc'
      path: '/openfgc'
      fullPath: '/openfgc'
      preLoaderRoute: typeof OpenfgcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OpenfgcRoute: OpenfgcRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
