/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PapersSlugRouteImport } from './routes/papers.$slug'
import { Route as ExploreDatasetRouteImport } from './routes/explore.$dataset'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersSlugRoute = PapersSlugRouteImport.update({
  id: '/papers/$slug',
  path: '/papers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreDatasetRoute = ExploreDatasetRouteImport.update({
  id: '/explore/$dataset',
  path: '/explore/$dataset',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore/$dataset': typeof ExploreDatasetRoute
  '/papers/$slug': typeof PapersSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore/$dataset': typeof ExploreDatasetRoute
  '/papers/$slug': typeof PapersSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore/$dataset': typeof ExploreDatasetRoute
  '/papers/$slug': typeof PapersSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/explore/$dataset' | '/papers/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/explore/$dataset' | '/papers/$slug'
  id: '__root__' | '/' | '/explore/$dataset' | '/papers/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreDatasetRoute: typeof ExploreDatasetRoute
  PapersSlugRoute: typeof PapersSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers/$slug': {
      id: '/papers/$slug'
      path: '/papers/$slug'
      fullPath: '/papers/$slug'
      preLoaderRoute: typeof PapersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/$dataset': {
      id: '/explore/$dataset'
      path: '/explore/$dataset'
      fullPath: '/explore/$dataset'
      preLoaderRoute: typeof ExploreDatasetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreDatasetRoute: ExploreDatasetRoute,
  PapersSlugRoute: PapersSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
