import { uswdsA11ySummarySchema, type UswdsA11ySummary } from "datasets";
import summaryJson from "../generated/uswds-a11y.json";

/** Figure-grade summary generated by tools/etl; validated at module load. */
export const uswdsSummary: UswdsA11ySummary = uswdsA11ySummarySchema.parse(summaryJson);

export type PaperStatus = "in-progress" | "preregistered" | "published";

export interface Paper {
  slug: string;
  title: string;
  status: PaperStatus;
  question: string;
  abstract: string[];
  datasetId: string;
  preregistrationHref: string;
}

export const papers: Paper[] = [
  {
    slug: "design-systems-accessibility",
    title: "Do design systems deliver accessibility at scale?",
    status: "preregistered",
    question:
      "Is graded adoption of a design system associated with fewer automatically detectable accessibility violations on real production websites?",
    abstract: [
      "Design systems promise consistency, and their maintainers increasingly promise accessibility: components ship with semantics, focus management, and contrast decisions already made. That promise has never been quantified at scale. This study uses the GSA Site Scanning programme - which scans ~26,000 US federal websites daily and records both a graded US Web Design System adoption signal and axe-core accessibility violations - to estimate the association between design-system adoption and accessibility outcomes across thousands of production sites operating under a single legal accessibility regime (Section 508).",
      "Preliminary descriptives show a monotone dose-response gradient: sites with no USWDS signal average 6.3 detected violations (24% violation-free), while sites with strong adoption signals average 2.5 (51% violation-free). Sites on USWDS v3 show fewer violations than sites on v2. These are unadjusted associations; the pre-registered analysis adds agency fixed effects, digital-maturity controls, and category-level outcomes, with diagnostics for adoption self-selection.",
      "The specification will be frozen before confirmatory estimation, then applied once to a held-out replication sample we collect ourselves: a scan of UK public-sector websites combining govuk-frontend detection with axe-core - testing, with new data, the Government Digital Service's published claim that the GOV.UK Design System helps services reach WCAG faster.",
    ],
    datasetId: "uswds-a11y",
    preregistrationHref:
      "https://github.com/deltoidgg/portfolio-2026/blob/main/docs/research/paper-01-design-systems-a11y/PREREGISTRATION.md",
  },
];

export function paperBySlug(slug: string): Paper | undefined {
  return papers.find((paper) => paper.slug === slug);
}
